// Catálogo de productos.
// Para AGREGAR un producto: copia una línea dentro de su categoría y cambia id/nombre.
// Para AGREGAR una categoría nueva: agrega un bloque nuevo con { clasificacion, unidad }.
// Formato de cada producto: [id, "nombre"]
// Si necesita una clasificación o unidad distinta a la de su categoría, se agrega como 3er/4to valor:
//   [id, "nombre", "Otra Clasificacion"]
//   [id, "nombre", null, "caja"]

const CATALOGO = {
  "Bebidas": {
    clasificacion: "Bebida Lata",
    unidad: "Pack",
    productos: [
      [1, "Bon Bon Durazno"],
      [2, "Bon Bon Uva"],
      [3, "Café Caja"],
      [4, "Dr.Peppers"],
      [5, "Dr.Peppers Frutilla"],
      [6, "Dr.Peppers Zero"],
      [7, "Leche De Frutilla"],
      [8, "Leche De Platano"],
      [9, "Leche De Taro"],
      [10, "Mango Sparkling"],
      [11, "Melon Soda"],
      [12, "Milky"],
      [13, "Pamls Coco Durazno"],
      [14, "Pamls Coco Mango"],
      [15, "Pamls Coco Uva"],
      [16, "Pear Juice"],
      [17, "Pear Juice Grande"],
      [18, "Plum Soda"],
      [19, "Pororo Bluberry"],
      [20, "Pororo Frutilla"],
      [21, "Pororo Manzana"],
      [22, "Pororo Milky"],
      [23, "Sparking Watermelon"],
      [24, "Tams Durazno Cero"],
      [25, "Tams Limon"],
      [26, "Welchs Cereza"],
      [27, "Welchs Frutilla"],
      [28, "Welchs Uva Morada"],
      [29, "Welchs Uva Verde"],
      [30, "Welchs Uva Verde Zero"],
      [31, "Café Instaneo Caja"],
      [32, "Café Instaneo Unidad"],
      [33, "Coco Palm Yogurt"],
    ]
  },
  "Helados": {
    clasificacion: "Helados",
    unidad: "Caja",
    productos: [
      [35, "Arandano"],
      [36, "Barquillo Chocolate"],
      [37, "Barquillo Crema"],
      [38, "Barquillo Crema Y Fresa"],
      [39, "Choclo"],
      [40, "Cono Chocolate"],
      [41, "Cono Vainilla"],
      [42, "Cream Zero"],
      [43, "Crema Cookie Bingree"],
      [44, "Cubo De Chocolate"],
      [45, "Frappe Cream And Cookies"],
      [46, "Frappe Leche"],
      [47, "Melona"],
      [48, "Mochi De Vainilla"],
      [49, "Pescado Chocolate"],
      [50, "Pescado Crema Pastelera"],
      [51, "Pescado Poroto Rojo"],
      [52, "Wafle Vainilla"],
    ]
  },
  "Pouch": {
    clasificacion: "Jugo Pouch",
    unidad: "Caja",
    productos: [
      [53, "Bluberry"],
      [54, "Blue Lemon"],
      [55, "Cafe Caramel Macchiato"],
      [56, "Cafe Sweet Americano"],
      [57, "Grape"],
      [58, "Hazelnult"],
      [59, "Kiwi"],
      [60, "Lychee Ade"],
      [61, "Mango"],
      [62, "Orange"],
      [63, "Peach"],
      [64, "Pomergranate"],
      [65, "Strawberry"],
      [66, "Watermelon"],
    ]
  },
  "Ramen": {
    clasificacion: "Ramen Bolsa",
    unidad: "Caja",
    productos: [
      [67, "Buldak 4 Quesos"],
      [69, "Buldak Carbonara"],
      [71, "Buldak Negro"],
      [72, "Buldak Rose"],
      [74, "Chapaguetti"],
      [76, "Jin Jjajang"],
      [77, "Jin Mild"],
      [79, "Jin Ramen"],
      [80, "Jin Ramen Chikens"],
      [82, "Jin Veggie"],
      [83, "Kimchi"],
      [84, "Otoggui"],
      [87, "Sarigontang"],
      [89, "Shin Ramyun"],
      [91, "Sopa De Camaron"],
      [92, "Udong"],
      [99, "Yuguejang"],
    ]
  },
  "Pote": {
    clasificacion: "Ramen Pote",
    unidad: "Caja",
    productos: [
      [100, "Buldak 4 Quesos Pote"],
      [101, "Buldak Carbonara Pote", "Ramen pote"],
      [102, "Buldak Rose Pote"],
      [75, "Chapaguetti Pote", "Ramen pote"],
      [78, "Jin Mild Pote"],
      [81, "Jin Ramen Pote"],
      [85, "Pasta Gochujan", "Pasta"],
      [86, "Pasta Miso", "Pasta"],
      [88, "Sarigontang Pote"],
      [90, "Shin Ramyun Pote"],
      [93, "Udong Pote"],
    ]
  },
  "Yopokki": {
    clasificacion: "Tteopoki",
    unidad: "Caja",
    productos: [
      [96, "Yopokki Golden Onion Butter"],
      [94, "Yopokki Cheese"],
      [95, "Yopokki Galbi", null, "caja"],
      [97, "Yopokki Rose"],
      [98, "Yopokki Sweet Spicy"],
    ]
  },
  "Dulces": {
    clasificacion: "Snack Dulce",
    unidad: "Caja",
    productos: [
      [34, "Gomita Sorpresa"],
      [100, "Algas Nori Grande"],
      [101, "Algas Nori Pequeña"],
      [102, "Almendras Manteca Miel"],
      [103, "Aros De Cebolla"],
      [104, "Arroz Instantaneo"],
      [105, "Cabritas De Hamburguesa"],
      [106, "Cabritas De Hershey"],
      [107, "Cabritas De Queso"],
      [108, "Caramelo Durazno"],
      [109, "Caramelo Frutilla"],
      [110, "Caramelo Uva"],
      [111, "Cheetos Barbecue"],
      [112, "Cheetos Picante"],
      [113, "Choco Pick"],
      [114, "Corn Chips"],
      [115, "Doritos Late Night"],
      [116, "Doritos Spicy"],
      [117, "Gomita De Lichi"],
      [118, "Gomita Sorpresa Bolsa2"],
      [119, "Gomita Uva"],
      [120, "Gomita Uva Morada"],
      [121, "Gomitas Kiwi Dorada"],
      [122, "Gomitas Sorpresa Bolsa"],
      [123, "Honey Apple"],
      [124, "Honey Butter"],
      [125, "Jelly Cola"],
      [126, "Jelly Frutilla"],
      [127, "Jelly Manzana"],
      [128, "Kancho"],
      [129, "Kopito Individual"],
      [130, "Kopitto Bolsa"],
      [131, "Oreo"],
      [132, "Oreo Chocolate"],
      [133, "Papas De Ñame"],
      [134, "Pepero Almendra"],
      [135, "Pepero Chocolate"],
      [136, "Pepero Cookie"],
      [137, "Pepero Crunky"],
      [138, "Pepero White"],
      [139, "Promo"],
      [140, "Setas De Chocolate"],
      [141, "Setas De Fresa"],
      [142, "Sufle De Banana"],
      [143, "Sufle De Camaron"],
      [144, "Sufle De Pizza"],
      [145, "Sufle Maple"],
      [146, "Sufle Marisco"],
      [147, "Twitchui Cereza"],
      [148, "Twitchui Lemon"],
    ]
  },
  "Carnes": {
    clasificacion: "Carnes",
    unidad: "kg",
    productos: [
      [149,"Yangnyeom Chicken",],
      [150,"Bulgogi",],
      
      [152,"Donkatsu",],
      [232, "Jeyuk Bokkeum"],
      [233, "Pollo Frito Bolsa"],
      [234, ""],
      [235, ""],
      [236, "" ],
     
    ]
  },
  "Verduras": {
    clasificacion: "unidad",
    unidad: "kg",
    productos: [
      [153, "Cebolla"],
      [245, "Lechuga",null,"unidad"],
      [246, "Zanahoria"],
      [null, "Diente de León"],
      [null, "Zapallo Italiano",null,"unidad"],
      [null, "Pepino", null, "Unidad"],
    ]
  },
  "Aseo": {
    clasificacion: "Aseo",
    unidad: "Unidad",
    productos: [
      [154, "Bolsa mediana"],
      [155, "Cif"],
      [156, "Cloró"],
      [157, "Desengrasante"],
      [158, "Escoba"],
      [159, "Esponja viruta"],
      [160, "Esponjas"],
      [161, "Guantes"],
      [162, "Jabón dispensador"],
      [163, "Lava loza (no drinks)"],
      [164, "Limpia piso"],
      [165, "Limpia vidrio"],
      [166, "Papel de baño"],
      [167, "Paños"],
      [168, "Paños amarrillos"],
      [169, "Perfume ambiente"],
      [170, "Trapo de piso"],
      [171, "Alcohol"],
      
    ]
  },
  "Cocina": {
    clasificacion: "Cocina",
    unidad: "Unidad",
    productos: [
      [172, "Aceite Cocina"],
      [173, "Aceite Fritura"],
      [174, "Aceite Sesamo"],
      [175, "Alga Nori Gimbap"],
      [176, "Alga Nori Samgak"],
      [177, "Arroz"],
      [178, "Azúcar"],
      [179, "Gochujang"],
      [180, "Harina de trigo"],
      [181, "Hot chili Sauce siracha"],
      [182, "Sirope"],
      [183, "Kanikama"],
      [184, "Ketchup"],
      [185, "Mayonesa"],
      [186, "Mirín"],
      [187, "Mostaza"],
      [188, "Oden"],
      [189, "Polvo de aji"],
      [190, "Pimienta roja para Jeyuk"],
      [191, "Sal"],
      [192, "Sal de Mar"],
      [193, "Salsa Jeyuk"],
      [194, "Salsa Bulgogi"],
      [195, "Salsa de Ostra"],
      [196, "Salsa de Soja"],
      [197, "Sesamo"],
      [198, "Spam"],
      [199, "Atun"],
      [200, "Fideos de Camote"],
      [201, "Hongo Shitake"],
      [202, "Polvo Rosado Yangyeom"],
      [203, "Chuño"],
      [204, "Curry"],
      [205, "Polvo Fried Chickens Yangyeom"],
      [206, "Teokboki Sauce Powder"],
      [207, ""],
      [208, "Vinagre blanco"],
      [209, "Alusa"],
      [237, "Mandu"],
      [238, "Kin-mari"],
      [239, "Salchicha"],
      [240, "Queso entero"],
      [241, "Huevos"],
      [242, ""],
      [243, ""],
      [244, "Kimchi"],
    ]
  },
  "Insumos": {
    clasificacion: "Insumos",
    unidad: "Caja",
    productos: [
      [210, "Bolsas medianas"],
      [211, "Bombillas"],
      [212, "Cofia"],
      [213, "Envase Kimbap"],
      [214, "Envase Frituras"],
      [215, "Guantes M"],
      [216, "Guantes S"],
      [217, "Palitos"],
      [218, "Papel Nova"],
      [219, "Papel Fritura"],
      [220, "Platos"],
      [221, "Platos Ramyeon"],
      [222, "Rolló etiquetadora"],
      [223, "Rolló máquina"],
      [224, "Servilleta"],
      [225, "Tapa platos"],
      [226, "Tapa vaso"],
      [227, "Vaso"],
      [228, "Tickets Fiscal"],
      [229, "Tickets Getnet"],
      [230, "Tenedor"],
      [231, "Cucharas"],
      [, "Bolsas de papel"],
    ]
  },
};

// --- No edites debajo de esta línea: arma window.PRODUCTOS automáticamente ---
// Tip: para un producto NUEVO puedes dejar el id como null y se asigna solo.
//   [null, "Producto Nuevo"]

(function () {
  const todos = Object.values(CATALOGO).flatMap(def => def.productos);
  let siguienteId = Math.max(0, ...todos.map(([id]) => id || 0)) + 1;

  window.PRODUCTOS = Object.entries(CATALOGO).flatMap(([categoria, def]) =>
    def.productos.map(([id, nombre, clasificacion, unidad]) => ({
      id: id || siguienteId++,
      nombre,
      categoria,
      clasificacion: clasificacion || def.clasificacion,
      tipo: 'Producto',
      unidad: unidad || def.unidad,
      activo: true
    }))
  );
})();
