// Catálogo de productos.
// Para AGREGAR un producto: copia una línea dentro de su categoría y cambia id/nombre.
// Para AGREGAR una categoría nueva: agrega un bloque nuevo con { clasificacion, unidad }.
// Formato de cada producto: [id, "nombre"]
// Si necesita una clasificación o unidad distinta a la de su categoría, se agrega como 3er/4to valor:
//   [id, "nombre", "Otra Clasificacion"]
//   [id, "nombre", null, "caja"]

const CATALOGO = {
  "Bebidas": {
    clasificacion: "Bebida Lata",
    unidad: "Pack",
    productos: [
      [1, "Bon Bon Durazno"],
      [2, "Bon Bon Uva"],
      [3, "Café Caja"],
      [4, "Dr.Peppers"],
      [5, "Dr.Peppers Frutilla"],
      [6, "Dr.Peppers Zero"],
      [7, "Leche De Frutilla"],
      [8, "Leche De Platano"],
      [9, "Leche De Taro"],
      [10, "Mango Sparkling"],
      [11, "Melon Soda"],
      [12, "Milky"],
      [13, "Pamls Coco Durazno"],
      [14, "Pamls Coco Mango"],
      [15, "Pamls Coco Uva"],
      [16, "Pear Juice"],
      [17, "Pear Juice Grande"],
      [18, "Plum Soda"],
      [19, "Pororo Bluberry"],
      [20, "Pororo Frutilla"],
      [21, "Pororo Manzana"],
      [22, "Pororo Milky"],
      [23, "Sparking Watermelon"],
      [24, "Tams Durazno Cero"],
      [25, "Tams Limon"],
      [26, "Welchs Cereza"],
      [27, "Welchs Frutilla"],
      [28, "Welchs Uva Morada"],
      [29, "Welchs Uva Verde"],
      [30, "Welchs Uva Verde Zero"],
      [31, "Café Instaneo Caja"],
      [32, "Café Instaneo Unidad"],
      [33, "Coco Palm Yogurt"],
    ]
  },
  "Helados": {
    clasificacion: "Helados",
    unidad: "Caja",
    productos: [
      [35, "Arandano"],
      [36, "Barquillo Chocolate"],
      [37, "Barquillo Crema"],
      [38, "Barquillo Crema Y Fresa"],
      [39, "Choclo"],
      [40, "Cono Chocolate"],
      [41, "Cono Vainilla"],
      [42, "Cream Zero"],
      [43, "Crema Cookie Bingree"],
      [44, "Cubo De Chocolate"],
      [45, "Frappe Cream And Cookies"],
      [46, "Frappe Leche"],
      [47, "Melona"],
      [48, "Mochi De Vainilla"],
      [49, "Pescado Chocolate"],
      [50, "Pescado Crema Pastelera"],
      [51, "Pescado Poroto Rojo"],
      [52, "Wafle Vainilla"],
    ]
  },
  "Pouch": {
    clasificacion: "Jugo Pouch",
    unidad: "Caja",
    productos: [
      [53, "Bluberry"],
      [54, "Blue Lemon"],
      [55, "Cafe Caramel Macchiato"],
      [56, "Cafe Sweet Americano"],
      [57, "Grape"],
      [58, "Hazelnult"],
      [59, "Kiwi"],
      [60, "Lychee Ade"],
      [61, "Mango"],
      [62, "Orange"],
      [63, "Peach"],
      [64, "Pomergranate"],
      [65, "Strawberry"],
      [66, "Watermelon"],
    ]
  },
  "Ramen": {
    clasificacion: "Ramen Bolsa",
    unidad: "Caja",
    productos: [
      [67, "Buldak 4 Quesos"],
      [69, "Buldak Carbonara"],
      [71, "Buldak Negro"],
      [72, "Buldak Rose"],
      [74, "Chapaguetti"],
      [76, "Jin Jjajang"],
      [77, "Jin Mild"],
      [79, "Jin Ramen"],
      [80, "Jin Ramen Chikens"],
      [82, "Jin Veggie"],
      [83, "Kimchi"],
      [84, "Otoggui"],
      [87, "Sarigontang"],
      [89, "Shin Ramyun"],
      [91, "Sopa De Camaron"],
      [92, "Udong"],
      [99, "Yuguejang"],
    ]
  },
  "Pote": {
    clasificacion: "Ramen Pote",
    unidad: "Caja",
    productos: [
      [100, "Buldak 4 Quesos Pote"],
      [101, "Buldak Carbonara Pote", "Ramen pote"],
      [102, "Buldak Rose Pote"],
      [103, "Chapaguetti Pote", "Ramen pote"],
      [104, "Jin Mild Pote"],
      [105, "Jin Ramen Pote"],
      [106, "Pasta Gochujan", "Pasta"],
      [107, "Pasta Miso", "Pasta"],
      [108, "Sarigontang Pote"],
      [109, "Shin Ramyun Pote"],
      [110, "Udong Pote"],
    ]
  },
  "Yopokki": {
    clasificacion: "Tteopoki",
    unidad: "Caja",
    productos: [
      [111, "Yopokki Golden Onion Butter"],
      [112, "Yopokki Cheese"],
      [113, "Yopokki Galbi", null, "caja"],
      [114, "Yopokki Rose"],
      [115, "Yopokki Sweet Spicy"],
    ]
  },
  "Dulces": {
    clasificacion: "Snack Dulce",
    unidad: "Caja",
    productos: [
      [116, "Gomita Sorpresa"],
      [117, "Algas Nori Grande"],
      [118, "Algas Nori Pequeña"],
      [119, "Almendras Manteca Miel"],
      [120, "Aros De Cebolla"],
      [121, "Arroz Instantaneo"],
      [122, "Cabritas De Hamburguesa"],
      [123, "Cabritas De Hershey"],
      [124, "Cabritas De Queso"],
      [125, "Caramelo Durazno"],
      [126, "Caramelo Frutilla"],
      [127, "Caramelo Uva"],
      [128, "Cheetos Barbecue"],
      [129, "Cheetos Picante"],
      [130, "Choco Pick"],
      [131, "Corn Chips"],
      [132, "Doritos Late Night"],
      [133, "Doritos Spicy"],
      [134, "Gomita De Lichi"],
      [135, "Gomita Sorpresa Bolsa2"],
      [136, "Gomita Uva"],
      [137, "Gomita Uva Morada"],
      [138, "Gomitas Kiwi Dorada"],
      [139, "Gomitas Sorpresa Bolsa"],
      [140, "Honey Apple"],
      [141, "Honey Butter"],
      [142, "Jelly Cola"],
      [143, "Jelly Frutilla"],
      [144, "Jelly Manzana"],
      [145, "Kancho"],
      [146, "Kopito Individual"],
      [147, "Kopitto Bolsa"],
      [148, "Oreo"],
      [149, "Oreo Chocolate"],
      [150, "Papas De Ñame"],
      [151, "Pepero Almendra"],
      [152, "Pepero Chocolate"],
      [153, "Pepero Cookie"],
      [154, "Pepero Crunky"],
      [156, "Pepero White"],
      [157, "Promo"],
      [158, "Setas De Chocolate"],
      [159, "Setas De Fresa"],
      [160, "Sufle De Banana"],
      [161, "Sufle De Camaron"],
      [162, "Sufle De Pizza"],
      [163, "Sufle Maple"],
      [164, "Sufle Marisco"],
      [165, "Twitchui Cereza"],
      [166, "Twitchui Lemon"],
    ]
  },
  "Carnes": {
    clasificacion: "Carnes",
    unidad: "kg",
    productos: [
      [167,"Yangnyeom Chicken",],
      [168,"Bulgogi",],
      
      [169,"Donkatsu",],
      [170, "Jeyuk Bokkeum"],
      [171, "Pollo Frito Bolsa",null, "caja"],
      [172, "Pecguha de pollo"],
      [173, ""],
      [174, "" ],
     
    ]
  },
  "Verduras": {
    clasificacion: "unidad",
    unidad: "kg",
    productos: [
      [175, "Cebolla"],
      [176, "Lechuga",null,"unidad"],
      [177, "Zanahoria"],
      [178, "Diente de Dragon"],
      [179, "Zapallo Italiano",null,"unidad"],
      [180, "Pepino", null, "Unidad"],
      [181, "Papa"],
      [182, "Repollo", null, "Unidad"],
      [183, "Repollo Morado", null, "Unidad"],
       [184, "Espinaca", null, "Unidad"],

    ]
  },
  "Aseo": {
    clasificacion: "Aseo",
    unidad: "Unidad",
    productos: [
      [185, "Bolsa mediana"],
      [186, "Cif"],
      [187, "Cloró"],
      [188, "Desengrasante"],
      [189, "Escoba"],
      [190, "Esponja viruta"],
      [191, "Esponjas"],
      [192, "Guantes Amarillos"],
      [193, "Jabón dispensador"],
      [194, "Lava loza (no drinks)"],
      [195, "Limpia piso"],
      [196, "Limpia vidrio"],
      [197, "Papel de baño"],
      [198, "Paños"],
      [199, "Paños amarrillos"],
      [200, "Perfume ambiente"],
      [201, "Trapo de piso"],
      [202, "Alcohol"],
      
    ]
  },
  "Cocina": {
    clasificacion: "Cocina",
    unidad: "Unidad",
    productos: [
      [203, "Aceite Cocina"],
      [204, "Aceite Fritura"],
      [205, "Aceite Sesamo"],
      [206, "Alga Nori Gimbap"],
      [207, "Alga Nori Samgak"],
      [208, "Arroz"],
      [209, "Azúcar"],
      [210, "Gochujang"],
      [211, "Harina de trigo"],
      [212, "Hot chili Sauce siracha"],
      [213, "Sirope"],
      [214, "Kanikama"],
      [215, "Ketchup"],
      [216, "Mayonesa"],
      [217, "Mirín"],
      [218, "Mostaza"],
      [219, "Oden"],
      [220, "Polvo de aji"],
      [221, "Pimienta roja para Jeyuk"],
      [222, "Sal"],
      [223, "Sal de Mar"],
      [224, "Salsa Jeyuk"],
      [225, "Salsa Bulgogi"],
      [227, "Salsa de Ostra"],
      [228, "Salsa de Soja"],
      [229, "Sesamo"],
      [230, "Spam"],
      [231, "Atun"],
      [232, "Fideos de Camote"],
      [233, "Hongo Shitake"],
      [234, "Polvo Rosado Yangyeom"],
      [235, "Chuño"],
      [236, "Curry"],
      [237, "Polvo Fried Chickens Yangyeom"],
      [238, "Teokboki Sauce Powder"],
      [239, "Queso Laminado"],
      [240, "Vinagre blanco"],
      [241, "Alusa"],
      [242, "Mandu"],
      [243, "Kin-mari"],
      [244, "Salchicha"],
      [245, "Queso entero"],
      [246, "Huevos"],
      [247, "Champiñones"],
      [248, ""],
      [249, "Kimchi"],
    ]
  },
  "Insumos": {
    clasificacion: "Insumos",
    unidad: "Caja",
    productos: [
      [250, "Bolsas medianas"],
      [251, "Bombillas"],
      [252, "Cofia"],
      [253, "Envase Kimbap"],
      [254, "Envase Frituras"],
      [255, "Guantes M"],
      [256, "Guantes S"],
      [257, "Palitos"],
      [258, "Papel Nova"],
      [259, "Papel Fritura"],
      [260, "Platos"],
      [261, "Platos Ramyeon"],
      [262, "Rolló etiquetadora"],
      [263, "Papel nova máquina"],
      [264, "Servilleta"],
      [265, "Tapa platos"],
      [266, "Tapa vaso"],
      [267, "Vaso"],
      [268, "Tickets Fiscal"],
      [269, "Tickets Getnet"],
      [270, "Tenedor"],
      [271, "Cucharas"],
      [, "Bolsas de papel"],
    ]
  },
};

// --- No edites debajo de esta línea: arma window.PRODUCTOS automáticamente ---
// Tip: para un producto NUEVO puedes dejar el id como null y se asigna solo.
//   [null, "Producto Nuevo"]

(function () {
  const todos = Object.values(CATALOGO).flatMap(def => def.productos);
  let siguienteId = Math.max(0, ...todos.map(([id]) => id || 0)) + 1;

  window.PRODUCTOS = Object.entries(CATALOGO).flatMap(([categoria, def]) =>
    def.productos.map(([id, nombre, clasificacion, unidad]) => ({
      id: id || siguienteId++,
      nombre,
      categoria,
      clasificacion: clasificacion || def.clasificacion,
      tipo: 'Producto',
      unidad: unidad || def.unidad,
      activo: true
    }))
  );
})();
